version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/bhr
    overwrite: yes

permissions:
  - object: /home/ubuntu/app/bhr
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 744

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 120
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 120
      runas: ubuntu
